language: php

php:
  - 5.4
  - 5.5
  - hhvm

services:
  - redis-server
  - memcached
  - elasticsearch
  - mongodb

install:
  - composer self-update && composer --version
# core framework:
#  - composer require satooshi/php-coveralls 0.6.* --dev --prefer-dist
  - composer install --prefer-dist

before_script:
  - echo 'elasticsearch version ' && curl http://localhost:9200/
  - mysql -e 'CREATE DATABASE yiitest;';
  - psql -U postgres -c 'CREATE DATABASE yiitest;';
  - tests/unit/data/travis/sphinx-setup.sh

script:
#  - vendor/bin/phpunit --coverage-clover tests/unit/runtime/coveralls/clover.xml --verbose --exclude-group mssql,oci,wincache,xcache,zenddata,vendor
  - vendor/bin/phpunit --verbose --exclude-group mssql,oci,wincache,xcache,zenddata,vendor,memcache,memcached,cubrid,apc,mongodb

#after_script:
#  - php vendor/bin/coveralls
